/* (Beta) Export of data model Pen of the subject dataModel.Agrifood for a PostgreSQL database. Pending translation of enumerations and multityped attributes */
CREATE TYPE sex_type AS ENUM ('M', 'F', 'unknown', '');
CREATE TYPE Pen_type AS ENUM ('Pen');
CREATE TABLE Pen (
  "additionalInfo" JSON,
  "address" JSON,
  "alternateName" TEXT,
  "areaServed" TEXT,
  "arrivalTimestamp" TIMESTAMP,
  "avgGrowth" NUMERIC,
  "avgWeight" NUMERIC,
  "buildingId" JSON,
  "co2" NUMERIC,
  "companyId" JSON,
  "compartmentId" JSON,
  "dataProvider" TEXT,
  "dateCreated" TIMESTAMP,
  "dateModified" TIMESTAMP,
  "deadAnimalsSinceDateOfArrival" NUMERIC,
  "description" TEXT,
  "farmId" JSON,
  "feedConsumption" NUMERIC,
  "humidity" NUMERIC,
  "id" TEXT PRIMARY KEY,
  "lastUpdate" TIMESTAMP,
  "location" JSON,
  "luminosity" NUMERIC,
  "name" TEXT,
  "numAnimals" NUMERIC,
  "owner" JSON,
  "relatedSource" JSON,
  "seeAlso" JSON,
  "sex" sex_type,
  "source" TEXT,
  "temperature" NUMERIC,
  "type" Pen_type,
  "waterConsumption" NUMERIC,
  "weightStDev" NUMERIC
);